[package]
name = "StreamScreenClient"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
screenshots = "0.5.3"
default-net = "0.16.1"
ipnetwork = "0.20.0"
rayon = "1.10.0"
gethostname = "0.4.3"